-- Create messages table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist to avoid conflicts
DROP POLICY IF EXISTS "Allow public insertion of messages" ON messages;
DROP POLICY IF EXISTS "Allow authenticated view" ON messages;
DROP POLICY IF EXISTS "Allow authenticated update" ON messages;
DROP POLICY IF EXISTS "Allow authenticated delete" ON messages;

-- Allow anonymous users to insert messages (for contact form)
CREATE POLICY "Allow public insertion of messages" ON messages
FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Allow authenticated users (admins) to view all messages
CREATE POLICY "Allow authenticated view" ON messages
FOR SELECT TO authenticated USING (true);

-- Allow authenticated users (admins) to update messages (mark as read)
CREATE POLICY "Allow authenticated update" ON messages
FOR UPDATE TO authenticated USING (true);

-- Allow authenticated users (admins) to delete messages
CREATE POLICY "Allow authenticated delete" ON messages
FOR DELETE TO authenticated USING (true);
